macro(add_plugin name file)
  add_library(${name} SHARED ${file})
  target_link_libraries(${name} PRIVATE otherlib)
  target_compile_definitions(${name} PRIVATE OTHER_PLUGIN_LIBRARY)
endmacro()

add_plugin(other_management_plugin other_editor_management.cpp)
add_plugin(tcp_side_channel_plugin tcp_side_channel.cpp)
add_plugin(status_window_plugin status_window.cpp)
add_plugin(vm_debugger_plugin vm_debugger_window.cpp)