using System;
using System.Collections.Generic;

namespace Other
{
  struct ProjectConfig
  {
    public static List<string> ExpectedProjectPaths = new List<string> {
      "${project-folder}/${project-name}.toml", // will be .toml for environment config
      /// this will be generated by editor/other tools and should not be manually created
      // "${project-folder}/${project-name}.other",  // will be project file for specific project data and configuration
      "${project-folder}/CMakeLists.txt", // cmake build file for native code

      "${project-folder}/src", // source .cpp files for driver and other native code (should be largely invisible to user unless they want extreme control and to write native code)
      "${project-folder}/src/CMakeLists.txt",
      "${project-folder}/src/${project-name}-driver.cpp",
      "${project-folder}/src/${project-name}-driver.hpp",
      "${project-folder}/assets", // assets which is visible in the editor and other project inspection Other tools
      /// we leave build folder for completeness sake but it should be generated and screws things up if it is here
      // "${project-folder}/build", // build output folder, should be gitignored and generated
      "${project-folder}/.other",
    };

    public static Dictionary<string, string> TemplatePaths = new Dictionary<string, string> {
      { ".toml", "templates/app-environment-config.toml" },
      { ".cpp", "templates/app-driver.cpp" },
      { ".hpp", "templates/app-driver.hpp" },
    };

    public enum ProjectType
    {
      APPLICATION = 0,
      MODULE = 1,
    }
    public string ProjectName { get; set; }
    public string ProjectFolder { get; set; }
    public string ProjectEnvironmentConfigPath { get; set; }

    public ProjectConfig()
    {
      ProjectName = "MyOtherApp";
      ProjectFolder = "MyOtherApp";
      ProjectEnvironmentConfigPath = "app-config.toml";
    }

    public ProjectConfig(string name, string folder, string env_config_path)
    {
      ProjectName = name;
      ProjectFolder = folder;
      ProjectEnvironmentConfigPath = env_config_path;
    }
  };
}