[application]
core-log-level = "debug"

[rendering]
rendering-backend = "opengl"
window-size = { width = 1920, height = 1080 }

[scripting]
dotnet-modules = [
  "build/development-drivers/script-testing/csharp/Debug/DotnetTesting.dll"
]

[assets]
# test-model = "resources/models/bone-test-1.fbx"
# test-model = "resources/models/bone-test-2.fbx"
test-model = "resources/models/bone-test-3.fbx"
# test-model = "resources/models/spinning-torus.fbx"
# test-model = "resources/models/animated-suzanne3.fbx"
# test-model = "resources/models/suzanne3.fbx"