[application]
core-log-level = "warn"
# fix test logs, currently this is every test and does not have good information, should have a log
#   for each seperate test-case 
core-log-file = "logs/dev-test-log.log"

[rendering]
force-no-window = true

[scripting]
dotnet-bindings = "build/other-csharp-interop/${build-config}/OtherCsBindings.dll"
dotnet-runtime-config = "other-csharp-interop/resources/OtherCsBindings.runtimeconfig.json"
other-csharp = "build/other-csharp/${build-config}/OtherCs.dll"