[application]
name = "Other Tests"
metadata = [ 
  { key = "name", value = "Other Tests"}, 
  { key = "description", value = "Other Environment Project Tests"},
  { key = "author", value = "N/A"},
  { key = "version", value = "0.1.0"} 
]

[rendering]
force-no-window = true
[ui]
# enable = false
enable-environment-menu-bar = true

[scripting]
other-csharp = "build/other-csharp/${build-config}/OtherCs.dll"
dotnet-bindings = "build/other-csharp/${build-config}/OtherCsBindings.dll"
dotnet-runtime-config = "other-csharp-interop/resources/OtherCsBindings.runtimeconfig.json"
other-lua-directory = "other-lua-interop"