[driver]
boot-file = "resources/editor-assets/editor-boot.oasm"
plugins = [
  # { name = "Other Management", path = "build/other-editor/plugins/${build-config}/other_management_plugin.dll" },
  { name = "Tcp Side Channel", path = "build/other-editor/plugins/${build-config}/tcp_side_channel_plugin.dll" },
  { name = "VM Debugger", path = "build/other-editor/plugins/${build-config}/vm_debugger_plugin.dll" }
]

[application]
name = "Other Editor"
metadata = [ 
  { key = "name", value = "Other Editor"}, 
  { key = "description", value = "Other Environment Project Editor"},
  { key = "author", value = "N/A"},
  { key = "version", value = "0.1.0"} 
]
core-log-level = "info"
core-log-file = "logs/editor.log"
auto-play-loaded-scenes = false

[rendering]
ui-layout-ini = "resources/ui/editor-layout.ini"
imgui-font = "resources/fonts/BlexMonoNerdFont-Regular.ttf"
pipelines = [
  "resources/editor-assets/default-pipeline.toml"
]

[ui]
enable-environment-menu-bar = true

[scripting]
init-lua = "resources/editor.lua"
# runtime config for dotnet host
dotnet-runtime-config = "other-csharp-interop/resources/OtherCsBindings.runtimeconfig.json"
# a dll satisfying the Other Environment Bindings API requirements
dotnet-bindings = "build/other-csharp/${build-config}/OtherCsBindings.dll"
# a dll satisfying the Other Environment API requirements
other-csharp = "build/other-csharp/${build-config}/OtherCs.dll"
other-lua-directory = "other-lua-interop"
dotnet-modules = [
  "build/other-editor/dotnet/${build-config}/OtherEditorCs.dll"
]