[application]
name = "Other Editor"
metadata = [ 
  { key = "name", value = "Other Editor"}, 
  { key = "description", value = "Other Environment Project Editor"},
  { key = "author", value = "N/A"},
  { key = "version", value = "0.1.0"} 
]
core-log-level = "info"
core-log-file = "logs/editor.log"
auto-play-loaded-scenes = false

[driver]
plugins = [
  { name = "Editor Management Plugin", path = "build/other-editor/plugins/${build-config}/other_management_plugin.dll" }
]

[filesystem]
mounts = [
  { name = "editor-assets", type = "physical", path = "resources/editor-assets" }
]

[rendering]
ui-layout-ini = "resources/ui/editor-layout.ini"
# pipelines = [
#   { name = "Editor Pipeline", path = "resources/rendering/editor_pipeline.orpl" }
# ]

[ui]
enable-environment-menu-bar = false

[assets]
test-model = "resources/models/spinning-torus.fbx"

[scripting]
envrc-path = "resources/editor-rc.lua"
# runtime config for dotnet host
dotnet-runtime-config = "other-csharp-interop/resources/OtherCsBindings.runtimeconfig.json"
# a dll satisfying the Other Environment Bindings API requirements
dotnet-bindings = "build/other-csharp/${build-config}/OtherCsBindings.dll"
# a dll satisfying the Other Environment API requirements
other-csharp = "build/other-csharp/${build-config}/OtherCs.dll"
other-lua-directory = "resources/lua"

dotnet-modules = [
  "build/other-editor/dotnet/${build-config}/OtherEditorCs.dll",
  "build/script-testing/${build-config}/DotnetTesting.dll",
]