[application]
core-log-level = "debug"
core-log-file = "logs/editor.log"

[rendering]
backend = "opengl"
ui-layout-ini = "resources/ui/editor-layout.ini"
window-size = { width = 1920, height = 1080 }

[assets]
test-model = "resources/models/spinning-torus.fbx"

[scripting]
envrc-path = "resources/editor-rc.lua"
# bridge dll for C# interop (private API)
dotnet-bindings = "build/other-csharp/${build-config}/OtherCsBindings.dll"
dotnet-runtime-config = "other-csharp-interop/resources/OtherCsBindings.runtimeconfig.json"
# client dll for C# interop (public API)
other-csharp = "build/other-csharp/${build-config}/OtherCs.dll"

# bridge directory for lua script (Prublit API)
other-lua-directory = "resources/lua"

dotnet-modules = [
  "build/development-drivers/script-testing/csharp/Debug/DotnetTesting.dll"
]