//////////////////////////////////////////////////////////
///                image description                   ///
//////////////////////////////////////////////////////////
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout (rgba32f, binding = 0) uniform image2D image_output;

//////////////////////////////////////////////////////////
///                scene description                   ///
//////////////////////////////////////////////////////////
layout (std140) uniform scene_metadata {
  vec4 window_size;

  /// x = num_spheres, y = num_objects, z = num_materials, w = padding
  ivec4 scene_data;

  int samples_per_pixel;
  int max_depth;
};

int get_num_spheres() { return scene_data.x; }
int get_num_objects() { return scene_data.y; }
int get_num_materials() { return scene_data.z; }

bool debug_patch(ivec2 pixel, ivec2 bounds) {
  return pixel.x >= bounds.x && pixel.x <= bounds.y &&
         pixel.y >= bounds.x && pixel.y <= bounds.y;
}

vec4 get_debug_patch_color(int measuring_idx, int bar) {
  if (measuring_idx > bar) {
    return vec4(0, 1, 0, 1);
  } else {
    return vec4(1, 0, 0, 1);
  }
}

//////////////////////////////////////////////////////////
///    include order is very specific! don't change!   ///
//////////////////////////////////////////////////////////
#include "math.glsl"

#include "material.glsl"
#include "shapes.glsl"
#include "object.glsl"

#include "camera.glsl"
#include "ray.glsl"

void main() {
  ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
#ifdef DEBUG_PATCH
  if (debug_patch(pixel, ivec2(10, 20))) {
    imageStore(image_output, pixel, get_debug_patch_color(get_num_materials(), 1));
    return;
  }
#endif

  vec3 color = vec3(0);
  for (int i = 0; i < samples_per_pixel; ++i) {
    uint sample_seed = uint(pixel.x + pixel.y * 1920 + i * 73);
    vec2 random_sample = vec2(random_float(sample_seed), random_float(sample_seed));
    ray r = get_ray(pixel, random_sample);

    const float near_clip = 0.001f;
    color += cast_ray(r, interval(near_clip, infinity), max_depth);
  }
  color /= float(samples_per_pixel);

  imageStore(image_output, pixel, vec4(color, 1.0));
}