[application]
core-log-level = "debug"

[rendering]
backend = "opengl"
ui-layout-ini = "resources/ui/renderer-dev-layout.ini"
window-size = { width = 1920, height = 1080 }


[scripting]
other-lua-directory = "other-lua-interop"
dotnet-bindings = "build/other-csharp/${build-config}/OtherCsBindings.dll"
dotnet-runtime-config = "other-csharp-interop/resources/OtherCsBindings.runtimeconfig.json"
other-csharp = "build/other-csharp/${build-config}/OtherCs.dll"
dotnet-modules = [
  "build/development-drivers/script-testing/csharp/Debug/DotnetTesting.dll"
]

[assets]
# test-model = "resources/models/Rumba Dancing.fbx"
# test-model = "resources/models/Rumba Dancing.dae"
# test-model = "resources/models/bone-test-1.fbx"
# test-model = "resources/models/bone-test-2.fbx"
# test-model = "resources/models/bone-test-2-1.fbx"
# test-model = "resources/models/bone-test-2-1.dae"
# test-model = "resources/models/bone-test-2-1.glb"
# test-model = "resources/models/bone-test-2-2.dae"
# test-model = "resources/models/bone-test-3.fbx"
# test-model = "resources/models/bone-test-3.dae"
# test-model = "resources/models/bone-test-4.fbx"
test-model = "resources/models/spinning-torus.fbx"
# test-model = "resources/models/animated-suzanne3.fbx"
# test-model = "resources/models/suzanne3.fbx"