
[application]
metadata = [ 
  { key = "name", value = "Other Editor"}, 
  { key = "description", value = "Other Environment Project Editor"},
  { key = "author", value = "Other Team"},
  { key = "version", value = "0.1.0"} 
]
role = "server"
core-log-level = "info"
core-log-file = "logs/server.log"

[rendering]
backend = "headless"
ui-layout-ini = "resources/ui/server-ui-layout.ini"

[scripting]
dotnet-bindings = "build/other-csharp/${build-config}/OtherCsBindings.dll"
dotnet-runtime-config = "other-csharp-interop/resources/OtherCsBindings.runtimeconfig.json"
other-csharp = "build/other-csharp/${build-config}/OtherCs.dll"
other-lua-directory = "resources/lua"