/**
 * \file core/version.hpp
 **/
#ifndef OTHER_CORE_CORE_VERSION_HPP
#define OTHER_CORE_CORE_VERSION_HPP

#define OTHER_ENVIRONMENT_VERSION_MAJOR 0
#define OTHER_ENVIRONMENT_VERSION_MINOR 1
#define OTHER_ENVIRONMENT_VERSION_PATCH 0
#define OTHER_ENVIRONMENT_VERSION_STRING "0.1.0"

#endif  // OTHER_CORE_CORE_VERSION_HPP
