/**
 * \file ocmd_file_format_version.hpp
 **/
#ifndef OTHERLIB_VM_COMMAND_FILES_OCMD_FILE_FORMAT_VERSION_HPP
#define OTHERLIB_VM_COMMAND_FILES_OCMD_FILE_FORMAT_VERSION_HPP

#define OCMD_FILE_FORMAT_VERSION_MAJOR 0
#define OCMD_FILE_FORMAT_VERSION_MINOR 1
#define OCMD_FILE_FORMAT_VERSION_PATCH 0
#define OCMD_FILE_FORMAT_VERSION_STRING "0.1.0"

#endif  // OTHERLIB_VM_COMMAND_FILES_OCMD_FILE_FORMAT_VERSION_HPP
