// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SIMCONFIGSPEC_H_
#define FLATBUFFERS_GENERATED_SIMCONFIGSPEC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

struct Vector3;

struct Cell;
struct CellBuilder;

struct Simulation;
struct SimulationBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Vector3 FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t x_;
  uint64_t y_;
  uint64_t z_;

 public:
  Vector3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vector3(uint64_t _x, uint64_t _y, uint64_t _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  uint64_t x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  uint64_t y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  uint64_t z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vector3, 24);

struct Cell FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CellBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_ALIVE = 6
  };
  const Vector3 *position() const {
    return GetStruct<const Vector3 *>(VT_POSITION);
  }
  bool alive() const {
    return GetField<uint8_t>(VT_ALIVE, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Vector3>(verifier, VT_POSITION, 8) &&
           VerifyField<uint8_t>(verifier, VT_ALIVE, 1) &&
           verifier.EndTable();
  }
};

struct CellBuilder {
  typedef Cell Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(const Vector3 *position) {
    fbb_.AddStruct(Cell::VT_POSITION, position);
  }
  void add_alive(bool alive) {
    fbb_.AddElement<uint8_t>(Cell::VT_ALIVE, static_cast<uint8_t>(alive), 0);
  }
  explicit CellBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Cell> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Cell>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Cell> CreateCell(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Vector3 *position = nullptr,
    bool alive = false) {
  CellBuilder builder_(_fbb);
  builder_.add_position(position);
  builder_.add_alive(alive);
  return builder_.Finish();
}

struct Simulation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SimulationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TICK = 4,
    VT_DIMENSIONS = 6,
    VT_CELLS = 8
  };
  int32_t tick() const {
    return GetField<int32_t>(VT_TICK, 100);
  }
  const Vector3 *dimensions() const {
    return GetStruct<const Vector3 *>(VT_DIMENSIONS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Cell>> *cells() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Cell>> *>(VT_CELLS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TICK, 4) &&
           VerifyField<Vector3>(verifier, VT_DIMENSIONS, 8) &&
           VerifyOffset(verifier, VT_CELLS) &&
           verifier.VerifyVector(cells()) &&
           verifier.VerifyVectorOfTables(cells()) &&
           verifier.EndTable();
  }
};

struct SimulationBuilder {
  typedef Simulation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tick(int32_t tick) {
    fbb_.AddElement<int32_t>(Simulation::VT_TICK, tick, 100);
  }
  void add_dimensions(const Vector3 *dimensions) {
    fbb_.AddStruct(Simulation::VT_DIMENSIONS, dimensions);
  }
  void add_cells(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Cell>>> cells) {
    fbb_.AddOffset(Simulation::VT_CELLS, cells);
  }
  explicit SimulationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Simulation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Simulation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Simulation> CreateSimulation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t tick = 100,
    const Vector3 *dimensions = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Cell>>> cells = 0) {
  SimulationBuilder builder_(_fbb);
  builder_.add_cells(cells);
  builder_.add_dimensions(dimensions);
  builder_.add_tick(tick);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Simulation> CreateSimulationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t tick = 100,
    const Vector3 *dimensions = nullptr,
    const std::vector<::flatbuffers::Offset<Cell>> *cells = nullptr) {
  auto cells__ = cells ? _fbb.CreateVector<::flatbuffers::Offset<Cell>>(*cells) : 0;
  return CreateSimulation(
      _fbb,
      tick,
      dimensions,
      cells__);
}

inline const Simulation *GetSimulation(const void *buf) {
  return ::flatbuffers::GetRoot<Simulation>(buf);
}

inline const Simulation *GetSizePrefixedSimulation(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Simulation>(buf);
}

inline const char *SimulationIdentifier() {
  return "osim";
}

inline bool SimulationBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SimulationIdentifier());
}

inline bool SizePrefixedSimulationBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SimulationIdentifier(), true);
}

inline bool VerifySimulationBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Simulation>(SimulationIdentifier());
}

inline bool VerifySizePrefixedSimulationBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Simulation>(SimulationIdentifier());
}

inline const char *SimulationExtension() {
  return "osim";
}

inline void FinishSimulationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Simulation> root) {
  fbb.Finish(root, SimulationIdentifier());
}

inline void FinishSizePrefixedSimulationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Simulation> root) {
  fbb.FinishSizePrefixed(root, SimulationIdentifier());
}

#endif  // FLATBUFFERS_GENERATED_SIMCONFIGSPEC_H_
