/**
 * \file vm/diagnostics/error_codes.hpp
 **/
#ifndef OTHERLIB_VM_DIAGNOSTICS_ERROR_CODES_HPP
#define OTHERLIB_VM_DIAGNOSTICS_ERROR_CODES_HPP

#include <array>
#include <string>
#include <string_view>

namespace other {

  enum vm_error_code : uint16_t {
    VM_UNKNOWN_ERROR = 0x0000,

    LEX_INVALID_CHAR,
    LEX_UNTERMINATED_STRING,
    LEX_MULTIPLE_DECIMAL,
    LEX_NUMBER_OUT_OF_RANGE,
    LEX_UNTERMINATED_COMMENT,

    PARSE_EMPTY_TOKEN_STREAM,
    PARSE_INVALID_TOKEN_STREAM,
    PARSE_UNEXPECTED_TOKEN,
    PARSE_EXPECTED_TOKEN,
    PARSE_UNKNOWN_DIRECTIVE,
    PARSE_UNKNOWN_OPCODE_KEYWORD,
    PARSE_TOO_MANY_OPERANDS,
    PARSE_DUPLICATE_DATA_OBJ,

    LINK_UNRESOLVED_SYMBOL,

    COMPILER_UNDEFINED_LABEL,
    COMPILER_UNUSED_LABEL,

    LEX_TRACE,
    PARSE_TRACE,
    LINK_TRACE,
    COMPILER_TRACE,

    LEX_INFO,
    PARSE_INFO,
    LINK_INFO,
    COMPILER_INFO,

    NUM_VM_ERROR_CODES,
    INVALID_VM_ERROR_CODE = NUM_VM_ERROR_CODES,
  };

}  // namespace other

#endif  // OTHERLIB_VM_DIAGNOSTICS_ERROR_CODES_HPP