/**
 * \file vm/simple_linking_tests.cpp
 **/
#include "vm_tests.hpp"

namespace other {

  // TEST_F(vm_tests, ocmd_simple_linking_main_fn) {
  //   const std::string_view source = R"(
  //   $main:
  //     ret
  //   end
  //   )";

  //   const auto program = detail::compile_source(source);
  //   ASSERT_TRUE(program.valid);
  //   ASSERT_EQ(program.compiled_blocks.size(), 1);
  //   ASSERT_TRUE(program.compiled_data_sections.empty());

  //   const std::vector<uint8_t> bytes = ocmd_linker{ program }.link(make_scope<default_symbol_resolver>());

  //   const std::vector<uint8_t> expected_bytes{
  //     0x4F, 0x43, 0x4D, 0x44,  // OCMD
  //     0x00, 0x00, 0x00, 0x24   // ret
  //   };

  //   ASSERT_EQ(bytes, expected_bytes);
  // }

  // TEST_F(vm_tests, ocmd_simple_linking_patch_code_label) {
  //   const std::string_view source = R"(
  //   $main:
  //     call helper
  //     ret
  //   end

  //   $helper:
  //     set r1, 7
  //     ret
  //   end
  //   )";

  //   const auto program = detail::compile_source(source);
  //   ASSERT_TRUE(program.valid);
  //   ASSERT_EQ(program.compiled_blocks.size(), 2);
  //   ASSERT_TRUE(program.compiled_data_sections.empty());

  //   const std::vector<uint8_t> bytes = ocmd_linker{ program }.link(make_scope<default_symbol_resolver>());

  //   // clang-format off
  //   const std::vector<uint8_t> expected_bytes {
  //     0x4F, 0x43, 0x4D, 0x44,  // OCMD
  //     0x08, 0x00, 0x00, 0x23,  // call helper at 0x0008
  //     0x00, 0x00, 0x00, 0x24,  // ret
  //     0x07, 0x00, 0x01, 0x12,  // set r1, 7
  //     0x00, 0x00, 0x00, 0x24,  // ret
  //   };
  //   // clang-format on

  //   ASSERT_EQ(bytes, expected_bytes);
  // }

  TEST_F(vm_tests, ocmd_simple_linking_patch_data) {
    const std::string_view source = R"(
    #data {
      .number : int32 = 42
    }
    $main:
      set r1, data.number
      dump r1
      ret
    end
    )";

    const auto program = detail::compile_source(source);
    ASSERT_TRUE(program.valid);
    ASSERT_EQ(program.compiled_blocks.size(), 1);

    const std::array expected_main = {
      detail::expected_machine_instruction{ .expected_opcode = opcode_load_x_from(vm_register_idx::VM_R1, 0xFFFF) },
      detail::expected_machine_instruction{ .expected_opcode = opcode_dump_register_x(vm_register_idx::VM_R1) },
      detail::expected_machine_instruction{ .expected_opcode = opcode_return() },
    };

    detail::expect_compiled_code_block_matches(program.compiled_blocks[0], "main", false, expected_main);

    const std::vector<uint8_t> bytes = ocmd_linker{ program }.link(make_scope<default_symbol_resolver>());

    std::vector<uint8_t> expected_bytes{
      0x4F, 0x43, 0x4D, 0x44,  // OCMD
      0x0C, 0x00, 0x01, 0x11,  // load r1 from [0x000C] (data.number)
      0x00, 0x00, 0x01, 0x02,  // dump r1
      0x00, 0x00, 0x00, 0x24,  // ret
      // data section for .number
      0x2A, 0x00, 0x00, 0x00  // int32 value of 42
    };

    std::stringstream ss;
    ss << "Generated bytes:\n";
    for (size_t i = 0; i < bytes.size(); i += 4) {
      ss << std::format("0x{:04X}: {:02X} {:02X} {:02X} {:02X}\n", i, bytes[i], bytes[i + 1], bytes[i + 2], bytes[i + 3]);
    }
    ss << "Expected bytes:\n";
    for (size_t i = 0; i < expected_bytes.size(); i += 4) {
      ss << std::format("0x{:04X}: {:02X} {:02X} {:02X} {:02X}\n", i, expected_bytes[i], expected_bytes[i + 1], expected_bytes[i + 2], expected_bytes[i + 3]);
    }
    SCOPED_TRACE(ss.str());
    ASSERT_EQ(bytes, expected_bytes);
  }

}  // namespace other