/**
 * \file vm/simple_linking_tests.cpp
 **/
#include <gtest/gtest.h>

#include "vm/command_files/ocmd_headers.hpp"
#include "vm/command_files/ocmd_linker.hpp"
#include "vm/default_symbol_resolver.hpp"
#include "vm/opcode.hpp"

#include "vm_tests.hpp"

namespace other {
  namespace detail {

    ocmd_file_header create_expected_header() {
      return ocmd_file_header{
        // .file_signature = { 'O', 'C', 'M', 'D' },
        // .file_version_major = OCMD_FILE_FORMAT_VERSION_MAJOR,
        // .file_version_minor = OCMD_FILE_FORMAT_VERSION_MINOR,
        .prog_header = {
          // code section always starts right after the header
          .code_section_offset = sizeof(ocmd_file_header),
          .data_section_offset = 0,
          .data_table_offset = 0,
          .num_instructions = 0,
          .entry_point_address = 0,
        }
      };
    }

    std::vector<uint8_t> create_expected_header_bytes() {
      ocmd_file_header header = create_expected_header();
      std::span bytes{ reinterpret_cast<const uint8_t*>(&header), sizeof(header) };
      return std::vector<uint8_t>(bytes.begin(), bytes.end());
    }

    std::vector<uint8_t> get_expected_bytes(std::span<const uint8_t> program_bytes) {
      std::vector<uint8_t> expected_bytes;
      expected_bytes.append_range(create_expected_header_bytes());
      expected_bytes.append_range(program_bytes);
      return expected_bytes;
    }

    void verify_bytes(const std::vector<uint8_t>& actual, const std::vector<uint8_t>& expected) {
      std::span actual_view = std::span{ actual };
      std::span expected_view = std::span{ expected };

      std::stringstream ss;
      ss << "\nGenerated bytes:\n";
      for (size_t i = 0; i < std::ranges::size(actual_view); i += 4) {
        ss << std::format("0x{:04X}: {:02X} {:02X} {:02X} {:02X}\n", i, actual[i], actual[i + 1], actual[i + 2], actual[i + 3]);
      }
      ss << "Expected bytes:\n";
      for (size_t i = 0; i < std::ranges::size(expected_view); i += 4) {
        ss << std::format("0x{:04X}: {:02X} {:02X} {:02X} {:02X}\n", i, expected[i], expected[i + 1], expected[i + 2], expected[i + 3]);
      }
      SCOPED_TRACE(ss.str());

      EXPECT_EQ(actual_view.size(), expected_view.size()) << "Actual and expected byte sizes do not match";
    }

  }  // namespace detail

  TEST_F(vm_tests, ocmd_simple_linking_main_fn) {
    const std::string_view source = R"(
    $main:
      ret
    end
    )";

    const auto program = detail::compile_source(source);
    ASSERT_TRUE(program.valid);
    ASSERT_EQ(program.compiled_blocks.size(), 1);
    ASSERT_TRUE(program.compiled_data_sections.empty());

    const std::vector<uint8_t> bytes = ocmd_linker{ program }.link(make_scope<default_symbol_resolver>());

    const std::vector<uint8_t> code_bytes{
      0x00, 0x00, 0x00, 0x24,  // ret
      0x00, 0x00, 0x00, 0x00   // stopdev guard
    };
    const std::vector<uint8_t> expected_bytes = detail::get_expected_bytes(code_bytes);

    detail::verify_bytes(bytes, expected_bytes);
  }

  TEST_F(vm_tests, ocmd_simple_linking_patch_code_label) {
    const std::string_view source = R"(
    $main:
      call helper
      ret
    end

    $helper:
      set r1, 7
      ret
    end
    )";

    const auto program = detail::compile_source(source);
    ASSERT_TRUE(program.valid);
    ASSERT_EQ(program.compiled_blocks.size(), 2);
    ASSERT_TRUE(program.compiled_data_sections.empty());

    const std::vector<uint8_t> bytes = ocmd_linker{ program }.link(make_scope<default_symbol_resolver>());

    const std::vector<uint8_t> code_bytes{
      // $main
      0x08, 0x00, 0x00, 0x23,  // call helper at 0x0008
      0x00, 0x00, 0x00, 0x24,  // ret
      // $helper
      0x07, 0x00, 0x01, 0x12,  // set r1, 7
      0x00, 0x00, 0x00, 0x24,  // ret
      0x00, 0x00, 0x00, 0x00   // stopdev guard
    };
    const std::vector<uint8_t> expected_bytes = detail::get_expected_bytes(code_bytes);

    detail::verify_bytes(bytes, expected_bytes);
  }

  TEST_F(vm_tests, ocmd_simple_linking_patch_data) {
    const std::string_view source = R"(
    #data {
      .number : int32 = 42
    }
    $main:
      set r1, data.number
      dump r1
      ret
    end
    )";

    const auto program = detail::compile_source(source);
    ASSERT_TRUE(program.valid);
    ASSERT_EQ(program.compiled_blocks.size(), 1);

    const std::array expected_main = {
      detail::expected_machine_instruction{ .expected_opcode = opcode_load_x_from(vm_register_idx::VM_R1, 0xFFFF) },
      detail::expected_machine_instruction{ .expected_opcode = opcode_dump_register_x(vm_register_idx::VM_R1) },
      detail::expected_machine_instruction{ .expected_opcode = opcode_return() },
    };

    detail::expect_compiled_code_block_matches(program.compiled_blocks[0], "main", false, expected_main);

    auto resolver = make_scope<default_symbol_resolver>();
    std::vector<uint8_t> bytes = ocmd_linker{ program }.link(std::move(resolver));
    std::vector<uint8_t> code_bytes{
      // $main
      0x2C, 0x00, 0x01, 0x11,  // load r1 from [0x0030] (data.number)
      0x00, 0x00, 0x01, 0x02,  // dump r1
      0x00, 0x00, 0x00, 0x24,  // ret
      0x00, 0x00, 0x00, 0x00,  // stopdev guard
      // #data
      // .number
      0x30, 0x00, 0x00, 0x00  // int32 value of 42 @ [0x0030]
    };
    const std::vector<uint8_t> expected_bytes = detail::get_expected_bytes(code_bytes);

    detail::verify_bytes(bytes, expected_bytes);
  }

}  // namespace other