[project]
metadata = [ 
  { key = "name", value = "Test Project"}, 
  { key = "description", value = "Test Project"},
  { key = "author", value = "N/A"},
  { key = "version", value = "0.1.0"} 
]

[scripting]
cs_project = "test-project/TestProject.csproj"