"""Generates test-project/assets/scenes/stress-arena.oscn (stress harness + human
profiling target). Deterministic; rerun after tuning the constants below."""
import math
import os
import random

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))).replace("\\", "/")
OUT_PATH = os.path.join(REPO_ROOT, "test-project", "assets", "scenes", "stress-arena.oscn")

GRID = 12           # dynamic bodies per side, two layers -> GRID*GRID*2 bodies
LIGHTS = 20
AUDIO_SOURCES = 6
SCRIPTED = 12

FLOOR_MODEL = f"{REPO_ROOT}/resources/models/floor.fbx"
TORUS_MODEL = f"{REPO_ROOT}/resources/models/spinning-torus.fbx"
MATERIALS = [f"{REPO_ROOT}/test-project/assets/materials/{m}.omat" for m in ("glass", "gold", "donut", "floor")]
AUDIO_CLIP = f"{REPO_ROOT}/test-project/assets/audio/141695__copyc4t__levelup.wav"

BASIS = "i = [ 0.0, 0.0, 1.0 ]\nj = [ 0.0, 1.0, 0.0 ]\nk = [ -1.0, 0.0, 0.0 ]"


def fmt(v):
  return f"{v:.6g}" if isinstance(v, float) else str(v)


def vec(*vals):
  return "[ " + ", ".join(fmt(float(v)) for v in vals) + " ]"


def transform(out, pos, scale=(1, 1, 1), quat=(0, 0, 0, 0)):
  out.append("[objects.components.transform]")
  out.append(f"local_position = {vec(*pos)}")
  out.append(f"local_scale = {vec(*scale)}")
  out.append(f"local_rotation_quat = {vec(*quat)}")
  out.append("[objects.components.transform.local_basis]")
  out.append(BASIS)


def render(out, model, material, tint=(1, 1, 1, 1)):
  out.append("[objects.components.render]")
  out.append(f'model_asset_id = "{model}"')
  out.append(f'material_asset_id = "{material}"')
  out.append("visible = true")
  out.append(f"tint = {vec(*tint)}")


def static_box(out, half_extents):
  out.append("[objects.components.physics]")
  out.append("[objects.components.physics.settings]")
  out.append("body_type = 0")
  out.append("[objects.components.physics.settings.shape]")
  out.append("shape_kind = 1")
  out.append(f"half_extents = {vec(*half_extents)}")


def main():
  rng = random.Random(0x51A0E5)
  out = ["# other environment scene document", "# generated by tools/gen_stress_scene.py - edit the generator, not this file",
         "[scene]", "schema-version = 1", 'name = "stress-arena"', "clear-color = [ 0.05, 0.06, 0.08, 1.0 ]"]
  next_id = 1

  def begin(name, tags=None):
    nonlocal next_id
    out.append("")
    out.append("[[objects]]")
    out.append(f"id = {next_id}")
    out.append(f'name = "{name}"')
    if tags:
      out.append(f"tags = [ {', '.join(f'\"{t}\"' for t in tags)} ]")
    next_id += 1

  begin("Floor")
  transform(out, (0, -0.5, 0), scale=(6, 1, 6))
  render(out, FLOOR_MODEL, MATERIALS[3])
  static_box(out, (30, 0.5, 30))

  for i, (x, z, sx, sz) in enumerate([(0, -14, 14, 0.5), (0, 14, 14, 0.5), (-14, 0, 0.5, 14), (14, 0, 0.5, 14)]):
    begin(f"Wall{i}")
    transform(out, (x, 2.0, z), scale=(sx / 5.0, 4.0, sz / 5.0))
    render(out, FLOOR_MODEL, MATERIALS[3], tint=(0.6, 0.62, 0.66, 1.0))
    static_box(out, (sx, 2.0, sz))

  spacing = 26.0 / (GRID - 1)
  for layer, base_y in enumerate((6.0, 10.0)):
    for gx in range(GRID):
      for gz in range(GRID):
        x = -13.0 + gx * spacing + rng.uniform(-0.3, 0.3)
        z = -13.0 + gz * spacing + rng.uniform(-0.3, 0.3)
        y = base_y + rng.uniform(0.0, 1.5)
        sphere = (gx + gz + layer) % 2 == 0
        begin(f"Body_{layer}_{gx}_{gz}")
        transform(out, (x, y, z), scale=(0.4, 0.4, 0.4))
        render(out, TORUS_MODEL, MATERIALS[(gx + gz) % 2],
               tint=(0.4 + 0.6 * rng.random(), 0.4 + 0.6 * rng.random(), 0.4 + 0.6 * rng.random(), 1.0))
        out.append("[objects.components.physics]")
        out.append("[objects.components.physics.settings]")
        out.append("body_type = 2")
        out.append("[objects.components.physics.settings.shape]")
        if sphere:
          out.append("shape_kind = 2")
          out.append("radius = 0.45")
        else:
          out.append("shape_kind = 1")
          out.append(f"half_extents = {vec(0.4, 0.4, 0.4)}")

  for i in range(LIGHTS):
    angle = 2.0 * math.pi * i / LIGHTS
    x, z = 12.0 * math.cos(angle), 12.0 * math.sin(angle)
    hue = i / LIGHTS
    color = (0.5 + 0.5 * math.cos(2 * math.pi * hue), 0.5 + 0.5 * math.cos(2 * math.pi * (hue + 1 / 3)), 0.5 + 0.5 * math.cos(2 * math.pi * (hue + 2 / 3)))
    begin(f"Light{i}")
    transform(out, (x, 4.0, z), scale=(0.1, 0.1, 0.1))
    out.append("[objects.components.point-light]")
    out.append("[objects.components.point-light.light]")
    out.append(f"position = {vec(x, 4.0, z)}")
    out.append(f"color = {vec(color[0], color[1], color[2], 1.0)}")

  for i in range(AUDIO_SOURCES):
    angle = 2.0 * math.pi * i / AUDIO_SOURCES
    x, z = 8.0 * math.cos(angle), 8.0 * math.sin(angle)
    begin(f"Audio{i}")
    transform(out, (x, 1.5, z), scale=(0.2, 0.2, 0.2))
    out.append("[objects.components.audio-source]")
    out.append(f'clip_asset_id = "{AUDIO_CLIP}"')
    out.append("playing = true")
    out.append("looping = true")
    out.append(f"volume = {fmt(0.2 + 0.1 * (i % 3))}")
    out.append(f"pitch = {fmt(0.8 + 0.1 * i)}")
    out.append("bus = 2")
    out.append("spatial = true")
    out.append("min_distance = 1.0")
    out.append("max_distance = 40.0")
    out.append("doppler_factor = 1.0")

  for i in range(SCRIPTED):
    angle = 2.0 * math.pi * i / SCRIPTED
    x, z = 10.0 * math.cos(angle), 10.0 * math.sin(angle)
    begin(f"Scripted{i}")
    transform(out, (x, 0.5, z))
    out.append("[objects.components.script]")
    out.append('behaviors = [ "TestBehavior" ]')

  begin("Camera", tags=["main-camera"])
  transform(out, (0, 22, 34))
  out.append("[objects.components.camera]")
  out.append("[objects.components.camera.camera]")
  out.append(f"position = {vec(0, 22, 34)}")
  out.append(f"direction = {vec(0, -0.543, -0.8397)}")
  out.append("euler_angles = [ 0.0, 0.0, 0.0 ]")
  out.append("world_up = [ 0.0, 1.0, 0.0 ]")
  out.append("defocus_angle = 0.0")
  out.append("focus_dist = 10.0")
  out.append("image_width = 2.0")
  out.append("aspect_ratio = 0.85179853")
  out.append("samples_per_pixel = 100")
  out.append("max_bounce_depth = 50")
  out.append("fov = 60.0")
  out.append("sensitivity = 10.0")
  out.append("constrain_pitch = true")
  out.append("[objects.components.camera.camera.basis]")
  out.append("i = [ -1.0, 0.0, 0.0 ]")
  out.append("j = [ 0.0, 1.0, 0.0 ]")
  out.append("k = [ 0.0, 0.0, -1.0 ]")

  with open(OUT_PATH, "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")
  print(f"wrote {OUT_PATH}: {next_id - 1} objects")


if __name__ == "__main__":
  main()
