/**
 * \file theme/theme_tokens.hpp
 **/
#ifndef OTHER_UI_THEME_THEME_TOKENS_HPP
#define OTHER_UI_THEME_THEME_TOKENS_HPP

#include "theme/colors.hpp"

#define OTHER_UI_COLOR_TOKENS(X)                                                                           \
  X("core.red", other::ui::colors::kRed)                                                                   \
  X("core.balanced_red", other::ui::colors::kBalancedRed)                                                  \
  X("core.green", other::ui::colors::kGreen)                                                               \
  X("core.balanced_green", other::ui::colors::kBalancedGreen)                                              \
  X("core.blue", other::ui::colors::kBlue)                                                                 \
  X("core.balanced_blue", other::ui::colors::kBalancedBlue)                                                \
  X("core.purple", other::ui::colors::kPurple)                                                             \
  X("core.balanced_purple", other::ui::colors::kBalancedPurple)                                            \
  X("core.yellow", other::ui::colors::kYellow)                                                             \
  X("core.cyan", other::ui::colors::kCyan)                                                                 \
  X("core.orange", other::ui::colors::kOrange)                                                             \
  X("core.white", other::ui::colors::kWhite)                                                               \
  X("core.black", other::ui::colors::kBlack)                                                               \
  X("core.bg0", other::ui::colors::kBG0)                                                                   \
  X("core.bg1", other::ui::colors::kBG1)                                                                   \
  X("core.bg2", other::ui::colors::kBG2)                                                                   \
  X("core.bg3", other::ui::colors::kBG3)                                                                   \
  X("core.bg4", other::ui::colors::kBG4)                                                                   \
  X("core.panel", other::ui::colors::kPanel)                                                               \
  X("core.panel_hover", other::ui::colors::kPanelHover)                                                    \
  X("core.panel_active", other::ui::colors::kPanelActive)                                                  \
  X("core.popup", other::ui::colors::kPopup)                                                               \
  X("core.field", other::ui::colors::kField)                                                               \
  X("core.field_hover", other::ui::colors::kFieldHover)                                                    \
  X("core.field_focused", other::ui::colors::kFieldFocused)                                                \
  X("core.title_bar", other::ui::colors::kTitleBar)                                                        \
  X("core.title_bar_active", other::ui::colors::kTitleBarActive)                                           \
  X("core.menu_bar", other::ui::colors::kMenuBar)                                                          \
  X("core.status_bar", other::ui::colors::kStatusBar)                                                      \
  X("core.tab", other::ui::colors::kTab)                                                                   \
  X("core.tab_hover", other::ui::colors::kTabHover)                                                        \
  X("core.tab_active", other::ui::colors::kTabActive)                                                      \
  X("core.tab_unfocused", other::ui::colors::kTabUnfocused)                                                \
  X("core.scroll_bar", other::ui::colors::kScrollBar)                                                      \
  X("core.scroll_bar_hover", other::ui::colors::kScrollBarHover)                                           \
  X("core.scroll_bar_active", other::ui::colors::kScrollBarActive)                                         \
  X("core.tooltip_bg", other::ui::colors::kTooltipBG)                                                      \
  X("core.border_subtle", other::ui::colors::kBorderSubtle)                                                \
  X("core.border", other::ui::colors::kBorder)                                                             \
  X("core.border_strong", other::ui::colors::kBorderStrong)                                                \
  X("core.text_bright", other::ui::colors::kTextBright)                                                    \
  X("core.text", other::ui::colors::kText)                                                                 \
  X("core.text_muted", other::ui::colors::kTextMuted)                                                      \
  X("core.text_disabled", other::ui::colors::kTextDisabled)                                                \
  X("core.text_friendly_alert", other::ui::colors::kTextFriendlyAlert)                                     \
  X("core.text_unfriend_alert", other::ui::colors::kTextUnfriendAlert)                                     \
  X("core.text_error", other::ui::colors::kTextError)                                                      \
  X("core.text_value_type", other::ui::colors::kTextValueType)                                             \
  X("core.text_value_data", other::ui::colors::kTextValueData)                                             \
  X("core.friendly_error_red", other::ui::colors::kFriendlyErrorRed)                                       \
  X("core.accent", other::ui::colors::kAccent)                                                             \
  X("core.accent_hover", other::ui::colors::kAccentHover)                                                  \
  X("core.accent_active", other::ui::colors::kAccentActive)                                                \
  X("core.accent_warm", other::ui::colors::kAccentWarm)                                                    \
  X("core.accent_warm_hover", other::ui::colors::kAccentWarmHover)                                         \
  X("core.accent_cool", other::ui::colors::kAccentCool)                                                    \
  X("core.accent_cool_hover", other::ui::colors::kAccentCoolHover)                                         \
  X("core.accent_cool_alt", other::ui::colors::kAccentCoolAlt)                                             \
  X("core.accent_cool_alt_hover", other::ui::colors::kAccentCoolAltHover)                                  \
  X("core.highlight", other::ui::colors::kHighlight)                                                       \
  X("core.outline_focus", other::ui::colors::kOutlineFocus)                                                \
  X("core.outline_alt", other::ui::colors::kOutlineAlt)                                                    \
  X("core.selection", other::ui::colors::kSelection)                                                       \
  X("core.selection_hover", other::ui::colors::kSelectionHover)                                            \
  X("core.selection_soft", other::ui::colors::kSelectionSoft)                                              \
  X("core.info", other::ui::colors::kInfo)                                                                 \
  X("core.info_bg", other::ui::colors::kInfoBG)                                                            \
  X("core.success", other::ui::colors::kSuccess)                                                           \
  X("core.success_bg", other::ui::colors::kSuccessBG)                                                      \
  X("core.warning", other::ui::colors::kWarning)                                                           \
  X("core.warning_bg", other::ui::colors::kWarningBG)                                                      \
  X("core.error", other::ui::colors::kError)                                                               \
  X("core.error_bg", other::ui::colors::kErrorBG)                                                          \
  X("core.data_type", other::ui::colors::kDataType)                                                        \
  X("core.data_type_alt", other::ui::colors::kDataTypeAlt)                                                 \
  X("core.data_value", other::ui::colors::kDataValue)                                                      \
  X("core.button", other::ui::colors::kButton)                                                             \
  X("core.button_hover", other::ui::colors::kButtonHover)                                                  \
  X("core.button_active", other::ui::colors::kButtonActive)                                                \
  X("core.button_primary", other::ui::colors::kButtonPrimary)                                              \
  X("core.button_primary_hover", other::ui::colors::kButtonPrimaryHover)                                   \
  X("core.button_primary_active", other::ui::colors::kButtonPrimaryActive)                                 \
  X("core.button_danger", other::ui::colors::kButtonDanger)                                                \
  X("core.button_danger_hover", other::ui::colors::kButtonDangerHover)                                     \
  X("core.button_danger_active", other::ui::colors::kButtonDangerActive)                                   \
  X("core.slider_grab", other::ui::colors::kSliderGrab)                                                    \
  X("core.slider_grab_active", other::ui::colors::kSliderGrabActive)                                       \
  X("core.check_mark", other::ui::colors::kCheckMark)                                                      \
  X("core.header", other::ui::colors::kHeader)                                                             \
  X("core.header_hover", other::ui::colors::kHeaderHover)                                                  \
  X("core.header_active", other::ui::colors::kHeaderActive)                                                \
  X("core.resize_grip", other::ui::colors::kResizeGrip)                                                    \
  X("core.resize_grip_hover", other::ui::colors::kResizeGripHover)                                         \
  X("core.resize_grip_active", other::ui::colors::kResizeGripActive)                                       \
  X("core.separator", other::ui::colors::kSeparator)                                                       \
  X("core.separator_hover", other::ui::colors::kSeparatorHover)                                            \
  X("core.separator_active", other::ui::colors::kSeparatorActive)                                          \
  X("core.docking_preview", other::ui::colors::kDockingPreview)                                            \
  X("core.docking_empty_bg", other::ui::colors::kDockingEmptyBG)                                           \
  X("core.console_bg", other::ui::colors::kConsoleBG)                                                      \
  X("core.console_prompt", other::ui::colors::kConsolePrompt)                                              \
  X("core.console_command", other::ui::colors::kConsoleCommand)                                            \
  X("core.console_output", other::ui::colors::kConsoleOutput)                                              \
  X("core.console_hint", other::ui::colors::kConsoleHint)                                                  \
  X("core.console_info", other::ui::colors::kConsoleInfo)                                                  \
  X("core.console_warning", other::ui::colors::kConsoleWarning)                                            \
  X("core.console_error", other::ui::colors::kConsoleError)                                                \
  X("core.node_header_color", other::ui::colors::kNodeHeaderColor)                                         \
  X("core.node_header_hover_color", other::ui::colors::kNodeHeaderHoverColor)                              \
  X("core.node_body_color", other::ui::colors::kNodeBodyColor)                                             \
  X("core.node_text_color", other::ui::colors::kNodeTextColor)                                             \
  X("core.basic_node_link_color", other::ui::colors::kBasicNodeLinkColor)                                  \
  X("core.input_pin_color", other::ui::colors::kInputPinColor)                                             \
  X("core.output_pin_color", other::ui::colors::kOutputPinColor)                                           \
  X("core.data_link_color", other::ui::colors::kDataLinkColor)                                             \
  X("core.node_card_stroke_color", other::ui::colors::kNodeCardStrokeColor)                                \
  X("core.node_outline_color", other::ui::colors::kNodeOutlineColor)                                       \
  X("core.node_title_text_color", other::ui::colors::kNodeTitleTextColor)                                  \
  X("core.node_editor_background", other::ui::colors::kNodeEditorBackground)                               \
  X("core.mode_stopped_bar", other::ui::colors::kModeStoppedBar)                                           \
  X("core.mode_playing_bar", other::ui::colors::kModePlayingBar)                                           \
  X("core.mode_playing_tint", other::ui::colors::kModePlayingTint)                                         \
  X("inspector.bg", other::ui::colors::inspector::kBG)                                                     \
  X("inspector.border", other::ui::colors::inspector::kBorder)                                             \
  X("inspector.object_header_bg", other::ui::colors::inspector::kObjectHeaderBG)                           \
  X("inspector.object_name", other::ui::colors::inspector::kObjectName)                                    \
  X("inspector.object_tag", other::ui::colors::inspector::kObjectTag)                                      \
  X("inspector.object_id", other::ui::colors::inspector::kObjectID)                                        \
  X("inspector.component_header_bg", other::ui::colors::inspector::kComponentHeaderBG)                     \
  X("inspector.component_header_hover", other::ui::colors::inspector::kComponentHeaderHover)               \
  X("inspector.component_header_text", other::ui::colors::inspector::kComponentHeaderText)                 \
  X("inspector.component_body", other::ui::colors::inspector::kComponentBody)                              \
  X("inspector.component_separator", other::ui::colors::inspector::kComponentSeparator)                    \
  X("inspector.property_label", other::ui::colors::inspector::kPropertyLabel)                              \
  X("inspector.property_value_text", other::ui::colors::inspector::kPropertyValueText)                     \
  X("inspector.property_row_hover", other::ui::colors::inspector::kPropertyRowHover)                       \
  X("inspector.property_row_alt", other::ui::colors::inspector::kPropertyRowAlt)                           \
  X("inspector.property_separator", other::ui::colors::inspector::kPropertySeparator)                      \
  X("inspector.field_bg", other::ui::colors::inspector::kFieldBG)                                          \
  X("inspector.field_border", other::ui::colors::inspector::kFieldBorder)                                  \
  X("inspector.field_border_focused", other::ui::colors::inspector::kFieldBorderFocused)                   \
  X("inspector.field_border_error", other::ui::colors::inspector::kFieldBorderError)                       \
  X("inspector.vec_field_x", other::ui::colors::inspector::kVecFieldX)                                     \
  X("inspector.vec_field_y", other::ui::colors::inspector::kVecFieldY)                                     \
  X("inspector.vec_field_z", other::ui::colors::inspector::kVecFieldZ)                                     \
  X("inspector.vec_field_w", other::ui::colors::inspector::kVecFieldW)                                     \
  X("inspector.add_component_bg", other::ui::colors::inspector::kAddComponentBG)                           \
  X("inspector.add_component_hover", other::ui::colors::inspector::kAddComponentHover)                     \
  X("inspector.add_component_text", other::ui::colors::inspector::kAddComponentText)                       \
  X("inspector.override_marker", other::ui::colors::inspector::kOverrideMarker)                            \
  X("inspector.modified_marker", other::ui::colors::inspector::kModifiedMarker)                            \
  X("inspector.reset_button", other::ui::colors::inspector::kResetButton)                                  \
  X("inspector.reset_button_hover", other::ui::colors::inspector::kResetButtonHover)                       \
  X("hierarchy.bg", other::ui::colors::hierarchy::kBG)                                                     \
  X("hierarchy.border", other::ui::colors::hierarchy::kBorder)                                             \
  X("hierarchy.item_text", other::ui::colors::hierarchy::kItemText)                                        \
  X("hierarchy.item_text_selected", other::ui::colors::hierarchy::kItemTextSelected)                       \
  X("hierarchy.item_text_disabled", other::ui::colors::hierarchy::kItemTextDisabled)                       \
  X("hierarchy.item_hover", other::ui::colors::hierarchy::kItemHover)                                      \
  X("hierarchy.item_selected", other::ui::colors::hierarchy::kItemSelected)                                \
  X("hierarchy.item_selected_unfocused", other::ui::colors::hierarchy::kItemSelectedUnfocused)             \
  X("hierarchy.indent_guide", other::ui::colors::hierarchy::kIndentGuide)                                  \
  X("hierarchy.expand_arrow", other::ui::colors::hierarchy::kExpandArrow)                                  \
  X("hierarchy.expand_arrow_hover", other::ui::colors::hierarchy::kExpandArrowHover)                       \
  X("hierarchy.drop_target", other::ui::colors::hierarchy::kDropTarget)                                    \
  X("hierarchy.drop_target_line", other::ui::colors::hierarchy::kDropTargetLine)                           \
  X("hierarchy.drag_preview", other::ui::colors::hierarchy::kDragPreview)                                  \
  X("hierarchy.icon_visible", other::ui::colors::hierarchy::kIconVisible)                                  \
  X("hierarchy.icon_hidden", other::ui::colors::hierarchy::kIconHidden)                                    \
  X("hierarchy.icon_locked", other::ui::colors::hierarchy::kIconLocked)                                    \
  X("hierarchy.search_bg", other::ui::colors::hierarchy::kSearchBG)                                        \
  X("hierarchy.search_border", other::ui::colors::hierarchy::kSearchBorder)                                \
  X("hierarchy.search_border_focused", other::ui::colors::hierarchy::kSearchBorderFocused)                 \
  X("hierarchy.search_match", other::ui::colors::hierarchy::kSearchMatch)                                  \
  X("console.bg", other::ui::colors::console::kBG)                                                         \
  X("console.bg_alt", other::ui::colors::console::kBGAlt)                                                  \
  X("console.border", other::ui::colors::console::kBorder)                                                 \
  X("console.scroll_gutter", other::ui::colors::console::kScrollGutter)                                    \
  X("console.prompt_symbol", other::ui::colors::console::kPromptSymbol)                                    \
  X("console.prompt_text", other::ui::colors::console::kPromptText)                                        \
  X("console.prompt_cursor", other::ui::colors::console::kPromptCursor)                                    \
  X("console.prompt_bg", other::ui::colors::console::kPromptBG)                                            \
  X("console.prompt_border", other::ui::colors::console::kPromptBorder)                                    \
  X("console.command", other::ui::colors::console::kCommand)                                               \
  X("console.command_history", other::ui::colors::console::kCommandHistory)                                \
  X("console.output", other::ui::colors::console::kOutput)                                                 \
  X("console.trace", other::ui::colors::console::kTrace)                                                   \
  X("console.debug", other::ui::colors::console::kDebug)                                                   \
  X("console.info", other::ui::colors::console::kInfo)                                                     \
  X("console.warning", other::ui::colors::console::kWarning)                                               \
  X("console.error", other::ui::colors::console::kError)                                                   \
  X("console.fatal", other::ui::colors::console::kFatal)                                                   \
  X("console.hint", other::ui::colors::console::kHint)                                                     \
  X("console.autocomplete_bg", other::ui::colors::console::kAutocompleteBG)                                \
  X("console.autocomplete_border", other::ui::colors::console::kAutocompleteBorder)                        \
  X("console.autocomplete_selected", other::ui::colors::console::kAutocompleteSelected)                    \
  X("console.autocomplete_match", other::ui::colors::console::kAutocompleteMatch)                          \
  X("console.autocomplete_text", other::ui::colors::console::kAutocompleteText)                            \
  X("console.autocomplete_desc", other::ui::colors::console::kAutocompleteDesc)                            \
  X("console.timestamp", other::ui::colors::console::kTimestamp)                                           \
  X("console.source", other::ui::colors::console::kSource)                                                 \
  X("console.filter_inactive", other::ui::colors::console::kFilterInactive)                                \
  X("console.filter_hover", other::ui::colors::console::kFilterHover)                                      \
  X("console.result_value", other::ui::colors::console::kResultValue)                                      \
  X("console.result_type", other::ui::colors::console::kResultType)                                        \
  X("asset_browser.bg", other::ui::colors::asset_browser::kBG)                                             \
  X("asset_browser.border", other::ui::colors::asset_browser::kBorder)                                     \
  X("asset_browser.grid_card_bg", other::ui::colors::asset_browser::kGridCardBG)                           \
  X("asset_browser.grid_card_hover", other::ui::colors::asset_browser::kGridCardHover)                     \
  X("asset_browser.grid_card_selected", other::ui::colors::asset_browser::kGridCardSelected)               \
  X("asset_browser.grid_card_border", other::ui::colors::asset_browser::kGridCardBorder)                   \
  X("asset_browser.grid_card_border_selected", other::ui::colors::asset_browser::kGridCardBorderSelected)  \
  X("asset_browser.thumbnail_bg", other::ui::colors::asset_browser::kThumbnailBG)                          \
  X("asset_browser.file_name", other::ui::colors::asset_browser::kFileName)                                \
  X("asset_browser.file_name_selected", other::ui::colors::asset_browser::kFileNameSelected)               \
  X("asset_browser.breadcrumb_text", other::ui::colors::asset_browser::kBreadcrumbText)                    \
  X("asset_browser.breadcrumb_separator", other::ui::colors::asset_browser::kBreadcrumbSeparator)          \
  X("asset_browser.breadcrumb_current", other::ui::colors::asset_browser::kBreadcrumbCurrent)              \
  X("asset_browser.filter_inactive", other::ui::colors::asset_browser::kFilterInactive)                    \
  X("asset_browser.filter_hover", other::ui::colors::asset_browser::kFilterHover)                          \
  X("asset_browser.dir_tree_bg", other::ui::colors::asset_browser::kDirTreeBG)                             \
  X("asset_browser.dir_item_hover", other::ui::colors::asset_browser::kDirItemHover)                       \
  X("asset_browser.dir_item_selected", other::ui::colors::asset_browser::kDirItemSelected)                 \
  X("asset_browser.status_bar_bg", other::ui::colors::asset_browser::kStatusBarBG)                         \
  X("asset_browser.status_text", other::ui::colors::asset_browser::kStatusText)                            \
  X("asset_browser.search_field_bg", other::ui::colors::asset_browser::kSearchFieldBG)                     \
  X("asset_browser.search_field_border", other::ui::colors::asset_browser::kSearchFieldBorder)             \
  X("asset_browser.search_field_focused", other::ui::colors::asset_browser::kSearchFieldFocused)           \
  X("asset.texture", other::ui::colors::asset::kTexture)                                                   \
  X("asset.model_source", other::ui::colors::asset::kModelSource)                                          \
  X("asset.model", other::ui::colors::asset::kModel)                                                       \
  X("asset.animation", other::ui::colors::asset::kAnimation)                                               \
  X("asset.script_source", other::ui::colors::asset::kScriptSource)                                        \
  X("asset.script", other::ui::colors::asset::kScript)                                                     \
  X("asset.audio", other::ui::colors::asset::kAudio)                                                       \
  X("asset.scene", other::ui::colors::asset::kScene)                                                       \
  X("asset.material", other::ui::colors::asset::kMaterial)                                                 \
  X("asset.folder", other::ui::colors::asset::kFolder)                                                     \
  X("asset.unknown", other::ui::colors::asset::kUnknown)                                                   \
  X("texture.signature", other::ui::colors::texture::kSignature)                                           \
  X("texture.signature_hover", other::ui::colors::texture::kSignatureHover)                                \
  X("texture.signature_muted", other::ui::colors::texture::kSignatureMuted)                                \
  X("texture.header_tint", other::ui::colors::texture::kHeaderTint)                                        \
  X("texture.border_accent", other::ui::colors::texture::kBorderAccent)                                    \
  X("texture.checker_light", other::ui::colors::texture::kCheckerLight)                                    \
  X("texture.checker_dark", other::ui::colors::texture::kCheckerDark)                                      \
  X("texture.channel_r", other::ui::colors::texture::kChannelR)                                            \
  X("texture.channel_g", other::ui::colors::texture::kChannelG)                                            \
  X("texture.channel_b", other::ui::colors::texture::kChannelB)                                            \
  X("texture.channel_a", other::ui::colors::texture::kChannelA)                                            \
  X("texture.mip_slider", other::ui::colors::texture::kMipSlider)                                          \
  X("texture.zoom_border", other::ui::colors::texture::kZoomBorder)                                        \
  X("texture.pixel_grid_line", other::ui::colors::texture::kPixelGridLine)                                 \
  X("model_source.signature", other::ui::colors::model_source::kSignature)                                 \
  X("model_source.signature_hover", other::ui::colors::model_source::kSignatureHover)                      \
  X("model_source.signature_muted", other::ui::colors::model_source::kSignatureMuted)                      \
  X("model_source.header_tint", other::ui::colors::model_source::kHeaderTint)                              \
  X("model_source.border_accent", other::ui::colors::model_source::kBorderAccent)                          \
  X("model.signature", other::ui::colors::model::kSignature)                                               \
  X("model.signature_hover", other::ui::colors::model::kSignatureHover)                                    \
  X("model.signature_muted", other::ui::colors::model::kSignatureMuted)                                    \
  X("model.header_tint", other::ui::colors::model::kHeaderTint)                                            \
  X("model.border_accent", other::ui::colors::model::kBorderAccent)                                        \
  X("animation.signature", other::ui::colors::animation::kSignature)                                       \
  X("animation.signature_hover", other::ui::colors::animation::kSignatureHover)                            \
  X("animation.signature_muted", other::ui::colors::animation::kSignatureMuted)                            \
  X("animation.header_tint", other::ui::colors::animation::kHeaderTint)                                    \
  X("animation.border_accent", other::ui::colors::animation::kBorderAccent)                                \
  X("script_source.signature", other::ui::colors::script_source::kSignature)                               \
  X("script_source.signature_hover", other::ui::colors::script_source::kSignatureHover)                    \
  X("script_source.signature_muted", other::ui::colors::script_source::kSignatureMuted)                    \
  X("script_source.header_tint", other::ui::colors::script_source::kHeaderTint)                            \
  X("script_source.border_accent", other::ui::colors::script_source::kBorderAccent)                        \
  X("script_source.syntax_keyword", other::ui::colors::script_source::kSyntaxKeyword)                      \
  X("script_source.syntax_string", other::ui::colors::script_source::kSyntaxString)                        \
  X("script_source.syntax_number", other::ui::colors::script_source::kSyntaxNumber)                        \
  X("script_source.syntax_comment", other::ui::colors::script_source::kSyntaxComment)                      \
  X("script_source.syntax_type", other::ui::colors::script_source::kSyntaxType)                            \
  X("script_source.syntax_function", other::ui::colors::script_source::kSyntaxFunction)                    \
  X("script_source.syntax_operator", other::ui::colors::script_source::kSyntaxOperator)                    \
  X("script_source.lua_badge", other::ui::colors::script_source::kLuaBadge)                                \
  X("script_source.dotnet_badge", other::ui::colors::script_source::kDotnetBadge)                          \
  X("script_source.compile_success", other::ui::colors::script_source::kCompileSuccess)                    \
  X("script_source.compile_error", other::ui::colors::script_source::kCompileError)                        \
  X("script_source.compile_warning", other::ui::colors::script_source::kCompileWarning)                    \
  X("script_source.line_number", other::ui::colors::script_source::kLineNumber)                            \
  X("script_source.line_number_active", other::ui::colors::script_source::kLineNumberActive)               \
  X("script.signature", other::ui::colors::script::kSignature)                                             \
  X("script.signature_hover", other::ui::colors::script::kSignatureHover)                                  \
  X("script.signature_muted", other::ui::colors::script::kSignatureMuted)                                  \
  X("script.header_tint", other::ui::colors::script::kHeaderTint)                                          \
  X("script.border_accent", other::ui::colors::script::kBorderAccent)                                      \
  X("script.exposed_property", other::ui::colors::script::kExposedProperty)                                \
  X("script.bound_property", other::ui::colors::script::kBoundProperty)                                    \
  X("script.unbound_property", other::ui::colors::script::kUnboundProperty)                                \
  X("script.overridden_value", other::ui::colors::script::kOverriddenValue)                                \
  X("audio.signature", other::ui::colors::audio::kSignature)                                               \
  X("audio.signature_hover", other::ui::colors::audio::kSignatureHover)                                    \
  X("audio.signature_muted", other::ui::colors::audio::kSignatureMuted)                                    \
  X("audio.header_tint", other::ui::colors::audio::kHeaderTint)                                            \
  X("audio.border_accent", other::ui::colors::audio::kBorderAccent)                                        \
  X("scene.signature", other::ui::colors::scene::kSignature)                                               \
  X("scene.signature_hover", other::ui::colors::scene::kSignatureHover)                                    \
  X("scene.signature_muted", other::ui::colors::scene::kSignatureMuted)                                    \
  X("scene.header_tint", other::ui::colors::scene::kHeaderTint)                                            \
  X("scene.border_accent", other::ui::colors::scene::kBorderAccent)                                        \
  X("asset_editor.bg", other::ui::colors::asset_editor::kBG)                                               \
  X("asset_editor.panel", other::ui::colors::asset_editor::kPanel)                                         \
  X("asset_editor.field", other::ui::colors::asset_editor::kField)                                         \
  X("asset_editor.field_hover", other::ui::colors::asset_editor::kFieldHover)                              \
  X("asset_editor.border", other::ui::colors::asset_editor::kBorder)                                       \
  X("asset_editor.header_bg", other::ui::colors::asset_editor::kHeaderBG)                                  \
  X("asset_editor.text", other::ui::colors::asset_editor::kText)                                           \
  X("asset_editor.text_muted", other::ui::colors::asset_editor::kTextMuted)                                \
  X("asset_editor.property_label", other::ui::colors::asset_editor::kPropertyLabel)                        \
  X("asset_editor.property_sep", other::ui::colors::asset_editor::kPropertySep)                            \
  X("asset_editor.dirty_marker", other::ui::colors::asset_editor::kDirtyMarker)                            \
  X("asset_editor.read_only_overlay", other::ui::colors::asset_editor::kReadOnlyOverlay)                   \
  X("texture_editor.signature", other::ui::colors::texture_editor::kSignature)                             \
  X("texture_editor.signature_hover", other::ui::colors::texture_editor::kSignatureHover)                  \
  X("texture_editor.signature_muted", other::ui::colors::texture_editor::kSignatureMuted)                  \
  X("texture_editor.header_tint", other::ui::colors::texture_editor::kHeaderTint)                          \
  X("texture_editor.border_accent", other::ui::colors::texture_editor::kBorderAccent)                      \
  X("texture_editor.checker_light", other::ui::colors::texture_editor::kCheckerLight)                      \
  X("texture_editor.checker_dark", other::ui::colors::texture_editor::kCheckerDark)                        \
  X("texture_editor.channel_r", other::ui::colors::texture_editor::kChannelR)                              \
  X("texture_editor.channel_g", other::ui::colors::texture_editor::kChannelG)                              \
  X("texture_editor.channel_b", other::ui::colors::texture_editor::kChannelB)                              \
  X("texture_editor.channel_a", other::ui::colors::texture_editor::kChannelA)                              \
  X("script_source_editor.signature", other::ui::colors::script_source_editor::kSignature)                 \
  X("script_source_editor.signature_hover", other::ui::colors::script_source_editor::kSignatureHover)      \
  X("script_source_editor.signature_muted", other::ui::colors::script_source_editor::kSignatureMuted)      \
  X("script_source_editor.header_tint", other::ui::colors::script_source_editor::kHeaderTint)              \
  X("script_source_editor.border_accent", other::ui::colors::script_source_editor::kBorderAccent)          \
  X("script_source_editor.syntax_keyword", other::ui::colors::script_source_editor::kSyntaxKeyword)        \
  X("script_source_editor.syntax_string", other::ui::colors::script_source_editor::kSyntaxString)          \
  X("script_source_editor.syntax_number", other::ui::colors::script_source_editor::kSyntaxNumber)          \
  X("script_source_editor.syntax_comment", other::ui::colors::script_source_editor::kSyntaxComment)        \
  X("script_source_editor.syntax_type", other::ui::colors::script_source_editor::kSyntaxType)              \
  X("script_source_editor.syntax_function", other::ui::colors::script_source_editor::kSyntaxFunction)      \
  X("script_source_editor.syntax_operator", other::ui::colors::script_source_editor::kSyntaxOperator)      \
  X("script_source_editor.lua_badge", other::ui::colors::script_source_editor::kLuaBadge)                  \
  X("script_source_editor.dotnet_badge", other::ui::colors::script_source_editor::kDotnetBadge)            \
  X("script_source_editor.compile_success", other::ui::colors::script_source_editor::kCompileSuccess)      \
  X("script_source_editor.compile_error", other::ui::colors::script_source_editor::kCompileError)          \
  X("script_source_editor.compile_warning", other::ui::colors::script_source_editor::kCompileWarning)      \
  X("script_source_editor.line_number", other::ui::colors::script_source_editor::kLineNumber)              \
  X("script_source_editor.line_number_active", other::ui::colors::script_source_editor::kLineNumberActive) \
  X("script_editor.signature", other::ui::colors::script_editor::kSignature)                               \
  X("script_editor.signature_hover", other::ui::colors::script_editor::kSignatureHover)                    \
  X("script_editor.signature_muted", other::ui::colors::script_editor::kSignatureMuted)                    \
  X("script_editor.header_tint", other::ui::colors::script_editor::kHeaderTint)                            \
  X("script_editor.border_accent", other::ui::colors::script_editor::kBorderAccent)                        \
  X("script_editor.exposed_property", other::ui::colors::script_editor::kExposedProperty)                  \
  X("script_editor.bound_property", other::ui::colors::script_editor::kBoundProperty)                      \
  X("script_editor.unbound_property", other::ui::colors::script_editor::kUnboundProperty)                  \
  X("script_editor.overridden_value", other::ui::colors::script_editor::kOverriddenValue)                  \
  X("scene_object.signature", other::ui::colors::scene_object::kSignature)                                 \
  X("scene_object.signature_hover", other::ui::colors::scene_object::kSignatureHover)                      \
  X("scene_object.signature_muted", other::ui::colors::scene_object::kSignatureMuted)                      \
  X("scene_object.header_tint", other::ui::colors::scene_object::kHeaderTint)                              \
  X("scene_object.border_accent", other::ui::colors::scene_object::kBorderAccent)                          \
  X("scene_object.component_transform", other::ui::colors::scene_object::kComponentTransform)              \
  X("scene_object.component_renderer", other::ui::colors::scene_object::kComponentRenderer)                \
  X("scene_object.component_physics", other::ui::colors::scene_object::kComponentPhysics)                  \
  X("scene_object.component_script", other::ui::colors::scene_object::kComponentScript)                    \
  X("scene_object.component_audio", other::ui::colors::scene_object::kComponentAudio)                      \
  X("scene_object.component_point_light", other::ui::colors::scene_object::kComponentPointLight)           \
  X("scene_object.component_direction_light", other::ui::colors::scene_object::kComponentDirectionLight)   \
  X("scene_object.component_camera", other::ui::colors::scene_object::kComponentCamera)                    \
  X("scene_object.component_grid", other::ui::colors::scene_object::kComponentGrid)                        \
  X("scene_object.component_animation", other::ui::colors::scene_object::kComponentAnimation)              \
  X("scene_object.component_registry", other::ui::colors::scene_object::kComponentRegistry)                \
  X("scene_object.component_custom", other::ui::colors::scene_object::kComponentCustom)                    \
  X("scene_object.asset_slot_empty", other::ui::colors::scene_object::kAssetSlotEmpty)                     \
  X("scene_object.asset_slot_drag_hover", other::ui::colors::scene_object::kAssetSlotDragHover)            \
  X("scene_object.asset_slot_loading", other::ui::colors::scene_object::kAssetSlotLoading)                 \
  X("scene_object.asset_slot_filled", other::ui::colors::scene_object::kAssetSlotFilled)                   \
  X("scene_object.asset_slot_invalid", other::ui::colors::scene_object::kAssetSlotInvalid)

namespace other {

  struct color_token {
    const std::string_view name;
    const glm::vec4* ptr;
    const glm::vec4 default_value;
  };

  inline std::span<const color_token> color_token_table() {
    static const std::array table = {
#define X(name, var) color_token{ name, &var, var },
      OTHER_UI_COLOR_TOKENS(X)
#undef X
    };
    return table;
  }

}  // namespace other

#endif  // OTHER_UI_THEME_THEME_TOKENS_HPP