# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Dev Stability Assurance - Windows

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -S ${{ github.workspace }} -B ${{ github.workspace }}/build 

    - name: Build
      run: python ${{ github.workspace }}/cli.py -b -c=Release

    - name: Run Tests
      run: ctest --test-dir ${{ github.workspace }}/build --output-on-failure
      continue-on-error: true