name: Build And Test

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install regex

    - name: Configure CMake
      run: cmake --version && cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DBUILD_OTHER_TESTS=ON

    - name: Build
      run: python ${{ github.workspace }}/cli.py -b -c=${{ inputs.configuration }}

    - name: Run Tests
      run: python ${{ github.workspace }}/cli.py -ts -serialization_tests* -c=${{ inputs.configuration }}
      continue-on-error: true

    - name: Check Test Results
      run: |
        $lcconfig = "${{ inputs.configuration }}".ToLower()
        $respath = "${{ github.workspace }}\build\tests\${lcconfig}\test_results.xml"
        python ${{ github.workspace }}/tools/test-validation.py $respath

    - name: Write Config Env Var
      run: echo "CONFIGURATION=${{ inputs.configuration }}.ToLower()" >> $GITHUB_ENV

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: other-test-results-windows-${{ env.CONFIGURATION }}
        path: ${{ github.workspace }}/other_test_results.windows.${{ env.CONFIGURATION }}.xml