# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Dev Stability Assurance - Windows

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -S ${{ github.workspace }} -B ${{ github.workspace }}/build  -DBUILD_OTHER_TESTS=ON -DBUILD_DEVELOPMENT_DRIVERS=OFF

    - name: Build
      run: python ${{ github.workspace }}/cli.py -b -c=Release

    - name: Run Tests
      run: python ${{ github.workspace }}/cli.py -t -c=Release
      continue-on-error: true

    - name: Check Test Results
      run: |
        if [ -f ${{ github.workspace }}/other_test_results.xml ]; then
          echo "Test results found."
        else
          echo "Test results not found!"
          exit 1
        fi
        ## check if tests passed
        if grep -q 'failures="0"' ${{ github.workspace }}/other_test_results.xml; then
          echo "All tests passed."
        else
          echo "Some tests failed!"
          exit 1
        fi
      continue-on-error: true

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: other-test-results
        path: ${{ github.workspace }}/other_test_results.xml