name: Dev Stability Assurance - Windows/Debug

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test-debug:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install regex

    - name: Configure CMake
      run: cmake --version && cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug  -DBUILD_OTHER_TESTS=ON

    - name: Build
      run: python ${{ github.workspace }}/cli.py -b -c=Debug

    - name: Run Tests
      run: python ${{ github.workspace }}/cli.py -ts -serialization_tests* -c=Debug
      continue-on-error: true

    - name: Check Test Results
      run: python ${{ github.workspace }}/tools/test-validation.py ${{ github.workspace }}/other_test_results.windows.debug.xml

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: other-test-results-windows-debug
        path: ${{ github.workspace }}/other_test_results.windows.debug.xml