name: "Dev Stability Assurance - Windows/Debug"

on:
  push:
    branches: [ "dev" ]

jobs:
  dev-stability-assurance-windows:
    runs-on: windows-latest
    steps:
      - name: "Build and Test (Windows/Debug)"
        uses: ./.github/workflows/build-and-test-windows.yml
        with:
          configuration: Debug
      - name: "Build and Test (Windows/Release)"
        uses: ./.github/workflows/build-and-test-windows.yml
        with:
          configuration: Release